name: Update PM2.5 DB
on:
  schedule:
    - cron: '30 15 * * *'  # 每天 23:30 (台灣時間) +8
  workflow_dispatch:       # 可手動執行
jobs:
  curl-update-db:
    runs-on: ubuntu-latest
    steps:
      - name: Call /update-db endpoint
        run: curl -s https://pm25-project-57p0.onrender.com/update-db